version: '3'

services:
    redis:
        image: "redis"
        # ports:
        #     - 6379:6379
        # volumes:
        #     - ./config/redis.conf:/redis.conf
        # command: [ "redis-server", "/redis.conf" ]
    
    webv2:
        build: .
        command: python run_app.py
        volumes:
        - .:/code
        ports:
        - 5000:5000
        depends_on:
        - redis

    celeryv3:
        build: .
        command: celery worker -A worker.celery --loglevel=info --pool=solo 
        volumes:
        - .:/code
        depends_on:
        - redis


